"""Release notes builder — consumes a ChangeSet (from `docgen diff`), with schema
changes called out prominently and breaking-change candidates flagged."""

from __future__ import annotations

from docgen.diffing.engine import Change, ChangeSet, FieldChange
from docgen.renderers.docmodel import Callout, Document, Paragraph, Section, Table

_COLLECTION_TITLES = {
    "entities": "Tables (schema changes)",
    "global_option_sets": "Global choice sets",
    "security_roles": "Security roles",
    "field_security_profiles": "Field security profiles",
    "cloud_flows": "Cloud flows",
    "connection_references": "Connection references",
    "environment_variables": "Environment variables",
    "plugin_assemblies": "Plug-in assemblies",
    "plugin_steps": "Plug-in steps",
    "web_resources": "Web resources",
    "custom_connectors": "Custom connectors",
    "canvas_apps": "Canvas apps",
    "other_components": "Other components",
}

# Schema changes are called out first, then behavioural components.
_COLLECTION_ORDER = list(_COLLECTION_TITLES)


def _fmt_value(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, dict):
        name = value.get("logical_name") or value.get("name") or value.get("schema_name")
        return f"{{{name}}}" if name else "{…}"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) or "—"
    return str(value)


def _describe_field_change(fc: FieldChange) -> str:
    if fc.new is None and isinstance(fc.old, (dict, list)):
        return f"removed {fc.path}"
    if fc.old is None and isinstance(fc.new, (dict, list)):
        return f"added {fc.path}"
    return f"{fc.path}: {_fmt_value(fc.old)} -> {_fmt_value(fc.new)}"


def _change_label(change: Change) -> str:
    return f"{change.label} ({change.key})" if change.label and change.label != change.key else change.key


def _collection_section(collection: str, changes: list[Change]) -> Section:
    section = Section(f"{_COLLECTION_TITLES.get(collection, collection)} "
                      f"({sum(1 for c in changes if c.kind == 'added')} added, "
                      f"{sum(1 for c in changes if c.kind == 'removed')} removed, "
                      f"{sum(1 for c in changes if c.kind == 'modified')} changed)")
    rows = []
    for change in changes:
        if change.kind in ("added", "removed"):
            detail = ""
        else:
            detail = "; ".join(_describe_field_change(fc) for fc in change.field_changes[:12])
            if len(change.field_changes) > 12:
                detail += f"; … {len(change.field_changes) - 12} more"
        rows.append([
            _change_label(change),
            change.kind,
            "BREAKING" if change.breaking else "",
            detail,
        ])
    section.add(Table(headers=["Component", "Change", "Breaking?", "Detail"], rows=rows))
    return section


def build_release_notes(changeset: ChangeSet) -> Document:
    doc = Document(
        title=f"Release Notes — {changeset.solution_name}",
        subtitle=f"v{changeset.old_version} -> v{changeset.new_version} — generated by docgen from snapshot diff",
    )

    grouped = changeset.by_collection()
    summary = Section("Summary")
    if not changeset.changes:
        summary.add(Paragraph("No component changes detected between the two snapshots."))
        doc.add(summary)
        return doc
    summary.add(Table(
        headers=["Component type", "Added", "Removed", "Changed"],
        rows=[
            [_COLLECTION_TITLES.get(c, c),
             str(sum(1 for ch in grouped[c] if ch.kind == "added")),
             str(sum(1 for ch in grouped[c] if ch.kind == "removed")),
             str(sum(1 for ch in grouped[c] if ch.kind == "modified"))]
            for c in _COLLECTION_ORDER if c in grouped
        ],
    ))
    doc.add(summary)

    breaking = changeset.breaking_changes
    breaking_section = Section("Breaking-change candidates")
    if breaking:
        breaking_section.add(Callout(
            "risk",
            f"{len(breaking)} component(s) carry changes flagged as potentially breaking. "
            "Review each before deploying to environments running "
            f"v{changeset.old_version}.",
        ))
        rows = []
        for change in breaking:
            for flag in change.breaking:
                rows.append([_change_label(change), flag.reason, flag.evidence])
        breaking_section.add(Table(headers=["Component", "Why it may break", "Evidence"], rows=rows))
    else:
        breaking_section.add(Paragraph("No breaking-change candidates detected."))
    doc.add(breaking_section)

    for collection in _COLLECTION_ORDER:
        if collection in grouped:
            doc.add(_collection_section(collection, grouped[collection]))
    return doc
