"""Renderer base class and the context handed to every document renderer."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from docgen.config import DocgenConfig
from docgen.renderers.docmodel import Document, Paragraph, Placeholder
from docgen.snapshot.models import Snapshot

# A narrative provider takes (purpose, payload) and returns prose or None.
# Under --no-llm it always returns None and the renderer gets a Placeholder —
# doc renderers never know whether the LLM tier is on.
NarrativeProvider = Callable[[str, dict], "str | None"]


def offline_narrative(purpose: str, payload: dict) -> str | None:
    return None


@dataclass
class RenderContext:
    config: DocgenConfig
    out_dir: Path
    narrative_provider: NarrativeProvider = offline_narrative
    rules: dict = field(default_factory=dict)  # loaded rules yaml, keyed by file stem

    def narrative(self, purpose: str, payload: dict, hint: str):
        """Prose paragraph if the LLM tier supplied one, else a placeholder."""
        prose = self.narrative_provider(purpose, payload)
        if prose:
            return Paragraph(prose)
        return Placeholder(hint=hint)


class DocRenderer(ABC):
    key: str = ""
    title: str = ""

    def applies(self, snapshot: Snapshot) -> bool:  # noqa: ARG002 - part of the interface
        return True

    @abstractmethod
    def build(self, snapshot: Snapshot, ctx: RenderContext) -> Document: ...

    def subtitle(self, snapshot: Snapshot) -> str:
        s = snapshot.solution
        managed = "managed" if s.managed else "unmanaged"
        return f"{s.display_name or s.unique_name} v{s.version} ({managed}) — generated by docgen from solution metadata"
